#!/usr/bin/env bash
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common"
bit64=false
OPTIND=1
while getopts a: OPT; do
  case "$OPT" in
    a)
      common_arch="$OPTARG"
      ;;
    ?)
      exit 2
      ;;
  esac
done
shift "$(($OPTIND - 1))"
common_setup
export CT_PREFIX="${common_root_dir}/out/ctng"
cd crosstool-ng/
./bootstrap
./configure --enable-local
make -j`nproc`
if "$bit64"; then
  cp "${common_root_dir}/ctng_defconfig/64" defconfig
  ./ct-ng defconfig
  rm defconfig
else
  ./ct-ng arm-unknown-eabi
fi
env -u LD_LIBRARY_PATH ./ct-ng build -j`nproc`
