#!/usr/bin/env bash
set -eu
root_dir="$(cd "$(dirname"${BASH_SOURCE[0]}")" && pwd)"
prefix=arm-unknown-eabi-
OPTIND=1
while getopts p: OPT; do
  case "$OPT" in
    p)
      prefix="$OPTARG"
      ;;
    ?)
      exit 2
      ;;
  esac
done
shift "$(($OPTIND - 1))"
export PATH="${root_dir}/out/ctng/arm-unknown-eabi/bin:${PATH}"
cd balau-qemu-newlib
"${prefix}gcc" -mcpu=cortex-a8 -c -o test.o test.c
"${prefix}gcc" -c -g -O3 -std=c99 -o startup.o startup.s
"${prefix}gcc" -mcpu=cortex-a8 -nostartfiles -c -o syscalls.o syscalls.c
"${prefix}gcc" -nostartfiles -Ttest.ld -o test.elf startup.o test.o syscalls.o
"${prefix}objcopy" -O binary test.elf test.bin
