#!/usr/bin/env bash
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common"
OPTIND=1
while getopts a: OPT; do
  case "$OPT" in
    a)
      common_arch="$OPTARG"
      ;;
    ?)
      exit 2
      ;;
  esac
done
shift "$(($OPTIND - 1))"
common_setup
export CT_PREFIX="${common_ctng_out_dir}"
cd crosstool-ng/
./bootstrap
./configure --enable-local
make -j`nproc`
cp "${common_root_dir}/ctng_defconfig/${common_arch}" defconfig
./ct-ng defconfig
rm defconfig
env -u LD_LIBRARY_PATH ./ct-ng build -j`nproc`
