= Crosstool-NG Newlib Examples
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

Run one command, get bare metal arm UART minimal examples that run on QEMU or gem5, written in C using the C standard library via Newlib, with a clean toolchain built with Crosstool-NG. Tested on Ubuntu 18.04.

toc::[]

== Getting started

Clone, build and run on QEMU:

....
git clone https://github.com/cirosantilli/newlib-examples
cd newlib-examples
git submodule update --recursive
./build-ctng && ./build-qemu && ./build-samples && ./run
....

Outcome: QEMU starts, go to the terminal and type the keys:

* `'a'`
* `'b'`

and watch QEMU reply as you type with:

....
97: a
new alloc of 1 bytes at address 0x1A2E0
Heap end = 0x1B000
98: b
new alloc of 2 bytes at address 0x1A2E0
Heap end = 0x1B000
....

This example illustrates the following Newlib syscall implementations:

* `read` to get user UART input
* `write` to give UART output
* `sbrk` for `malloc`

=== gem5

Run on `gem5` instead of QEMU:

....
./build-gem5
./run -g
....

On another shell:

....
./gem5-shell
....

TODO: this is printing newlines without automatic carriage return `\r` as in:

....
enter a character
                 got: a
....

We use `m5term` by default, and if we try `telnet` instead:

....
telnet localhost 3456
....

it does add the carriage returns automatically.

=== Ubuntu distro toolchain

If you are really lazy, and don't want to wait 10 minutes for the toolchain or QEMU to build, you can also do just:

....
sudo apt-get install gcc-arm-none-eabi qemu-system-arm
./build-samples -p arm-none-eabi-
./run -h
....

Shame on you.

== Why this is cool

Usually, when you have to explain something, it is already not cool, but here goes in any case.

This allows you to run C programs without an operating system, directly on bare metal, and use a subset of the C standard library.

This allows you to run possibly unmodified C programs directly on bare metal.

Furthermore, we build a completely pristine GCC from source via crosstool-ng, therefore dispensing any distro provided blobs.

== Directory structure

=== ctng_defconfig

Contains crosstool-ng defconfigs. To generate those, do:

....
# Generates the base config.
./build-ctng
cd crosstool-ng
./ct-ng menuconfig
./ct-ng savedefconfig
cp defconfig ../../ctng_defconfig/<yourname>
....
