#!/usr/bin/env bash
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common"
host=false
OPTIND=1
while getopts a:h OPT; do
  case "$OPT" in
    a)
      common_arch="$OPTARG"
      ;;
    h)
      host=true
      ;;
    ?)
      exit 2
      ;;
  esac
done
shift "$(($OPTIND - 1))"
common_setup
root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if "$host"; then
  qemu_exec="$common_qemu_exec_basename"
else
  qemu_exec="$common_qemu_exec"
fi
"$qemu_exec" -M realview-pb-a8 -serial stdio -kernel "$common_bin"
