#!/usr/bin/env bash
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common"
OPTIND=1
while getopts a:dhgt OPT; do
  case "$OPT" in
    a)
      common_arch="$OPTARG"
      ;;
    ?)
      exit 2
      ;;
  esac
done
shift "$(($OPTIND - 1))"
common_setup
cmd="\
'${common_ctng_bin_dir}/${common_prefix}-gdb' \\
-ex 'target remote localhost:${common_gdb_port}' \\
'${common_elf}' \\
"
echo "$cmd"
eval "$cmd"
